repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=88, --target-version=py311]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3.11
        args: [--profile=black, --line-length=88, --filter-files]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
        types_or: [python, pyi]

  - repo: https://github.com/psf/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==24.4.0]
        args: [--line-length=88]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-python-dateutil]
        args: [--strict, --ignore-missing-imports, --show-error-codes]
        files: ^app/
        types: [python]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: [--recursive, --configfile=pyproject.toml]
        exclude: ^(tests?|examples?)/


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-toml@0.3.1
          - prettier-plugin-sort-json@0.0.2
        args: [--prose-wrap=always, --print-width=88, --write]
        types_or: [markdown, yaml, json, toml, html, css, scss, javascript, typescript, jsx, tsx]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []  # Use all available rules

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.15.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
        args: [--retry, --retry-fix, --allow-abort, --hook-mode, --commit-msg-file]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: [--recursive, --configfile=pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-python-dateutil]
        args: [--strict]
        exclude: ^tests/

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
