version: "3.8"

services:
  jam-splitter:
    build: .
    image: jam-splitter-agent:latest
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./output_stems:/home/agentuser/app/output_stems
      - ./cache.db:/home/agentuser/app/cache.db
    tty: true
    stdin_open: true
