apiVersion: v2
name: jamsplitter
description: A Helm chart for JamSplitter
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "11.6.12"
    repository: "https://charts.bitnami.com/bitnami"
  - name: redis
    version: "16.8.5"
    repository: "https://charts.bitnami.com/bitnami"
